server:
  port: 9090

spring:
  application:
    name: "BookManageSystem"
  thymeleaf:
    cache: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookmanagesystem?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: jqc004118
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: "classpath:mapper/*Mapper.xml"